general.import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Gruvbox-Dark.toml"
]
[font]
size = 11.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window]
startup_mode = "Fullscreen"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.69
blur = true 

[bell]
animation = "Linear"
duration = 30
color = "#ebddb2"
#command = "None"

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
thickness = 0.15
